### ISSUE TITLE
formlyField contain other 3rd party directive

### ISSUE THREAD

**Issue by SagiMedina** [formly-js/angular-formly#392] opened 2015-07-15 07:27 UTC
I'm using setType:
```        
formlyConfigProvider.setType({
    name: 'lx-file-input',
    templateUrl: '/static/hr/app/blocks/file_input_formly/file_input_formly.html'
});
```

And in my template i'm using a 3rd party directive.

My problem is that the formlyField directive append my template too late and the 3rd party directive wont compile at that time.

EDIT
could be another reason... 

Any thoughts? @kentcdodds

**Comment by kentcdodds** [comment] 2015-07-15 12:12
Hi @SagiMedina, it's hard for me to tell without seeing exactly what the issue is. Please create an example and follow the instructions here: http://help.angular-formly.com

I'm going to go ahead and close this issue. There are many ways you can get help, but the issues are reserved for bugs and feature requests.

**Closed by kentcdodds** 2015-07-15 12:12 UTC

**Comment by jajourda** [comment] 2015-10-22 21:02
I'm having the same problem:


<div class="input-section"><label for="" class="input-section-label"><span ng-bind-html="options.data.singleCardInstanceLabel | toTrusted"></span><span class="tip icon-question" popover-animation="true" popover="{{options.data.popover}}" type="button"></span></label>

<div class="input-section-input-wrap">

<pre>{{[options.key]|json}}</pre>

<input type="text" id="{{model[options.key]}}" ng-model="model[options.key]" cc-number=""></div>

</div>

trying to us 3rd-party directive cc-number
https://github.com/bendrucker/angular-credit-cards

**Comment by kentcdodds** [comment] 2015-10-22 21:48
Again, it's hard for me to help without an example following the instructions here: http://help.angular-formly.com

**Comment by jajourda** [comment] 2015-10-23 07:37
will work on doing that now. thanks.

**Comment by jajourda** [comment] 2015-10-23 08:57
Bro, bro, bro, bro :) I have to say I have really started to admire your work ethic and killer use of github for maintaining not just your codebase but your USERBASE (you're kind of ensuring quality control AND an increased adoption rate of your module). 

So, by sending everyone to http://help.angular-formly.com, you accomplish two things.

1.you make sure real problems get addressed
2. the flow of directions you offer on the help page makes sure that real problems are real problems (this is where I come in).

My "problem" was in fact not a problem at all, and having to explain it, document it, and reproduce it showed me I was thinking about the issue the wrong way. In case anyone else wants help with integrating ben drucker's super useful credit-cards with angualr-formly check out the following link based on the help form.
http://output.jsbin.com/gifalan

blessings to you and your family bro. thank you for an awesome repository :)

**Comment by kentcdodds** [comment] 2015-10-23 15:08
@jajourda thanks :blush: that's exactly why I direct people to http://help.angular-formly.com... I simply don't have time to triage issues myself. While doing this may be a little less helpful in the short-term, it does help people figure things out for themselves and they learn how angular-formly works so they have fewer questions in the future and they're able to use angular-formly more productively.

As a note to your specific example, you could pretty easily extend an existing type to add support for the cc-card attribute :-) I created an example and added it to the website: http://angular-formly.com/#/example/integrations/angular-credit-card

**Comment by kentcdodds** [comment] 2015-10-23 15:09
Note, there's [a bug](https://github.com/formly-js/angular-formly/issues/523) right now that's making this not work quite right, but hopefully that'll be resolved soon.
