### ISSUE TITLE
How to bind formly form to meteor object ($meteor.object) ?

### ISSUE THREAD

**Issue by abcd-ca** [formly-js/angular-formly#320] opened 2015-05-26 19:53 UTC
Hi Kent, I have a Meteor project with Ionic Framework and have gotten formly to work within it but not if I want to bind it to my Meteor (collection) object. If I can get that to work, I'll be able to have 3-way binding between UI, controller and Mongo.

Cheers,

Andrew

**Comment by kentcdodds** [comment] 2015-05-26 20:17
I'm not familiar with Meteor. I don't know how to help you. Please provide more information and [an example](http://jsbin.com/biqesi/edit) of the problem.

**Comment by abcd-ca** [comment] 2015-05-26 20:35
Thanks Kent, I understand. I think we need meteor to make this actually run but this is the distilled code: 
http://jsbin.com/feniwagetu/1/edit?html,css,js,output

Basically Meteor gives you objects (bound to mongodb documents) which do work with ng-model on <input> elements. However, formly doesn't seem to like these objects. 

In the console when I print out $scope.expedition it looks like this:
```
SubObject {_id: "QcJfgcmmtpMrqoWXj", owner: "L8PovFSsDsY9hfrSj", date: Tue May 26 2015 01:48:49 GMT-0700 (PDT), title: "ice cream", $$collection: C…s._…n.ns.Collection…}
```

You can see it's some special kind of object but does have the properties I'm trying to bind to like 'title'. It's OK if you can't help but if you're curious, this is an awesome place to start: http://angular-meteor.com/tutorial

**Comment by abcd-ca** [comment] 2015-05-26 20:43
by the way, this is the top of the error I'm getting:
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at _.extend.forEach
```

**Comment by kentcdodds** [comment] 2015-05-26 21:09
Sorry @abcd-ca. What I mean is I need something that actually runs and demonstrates the problem, not just some sample code. Everything you've shown seems like it should work just fine so I can't tell you what the problem is without being able to jump in a debugger. From that error, it appears that somewhere we're calling `Object.keys` on a `null` or `undefined` value.

**Comment by kentcdodds** [comment] 2015-05-26 21:09
Here are all the places we're doing that: https://github.com/formly-js/angular-formly/search?utf8=%E2%9C%93&q=Object.keys

**Comment by abcd-ca** [comment] 2015-05-26 21:28
Thanks for the lead Kent!

**Comment by kentcdodds** [comment] 2015-05-30 03:13
I'm going to go ahead and close this issue. Let me know if there's further help that I can give.

**Closed by kentcdodds** 2015-05-30 03:13 UTC
Labels: Community Help Please!

**Comment by estaub** [comment] 2015-09-06 00:04
I can shed some light, I think.  The problem occurs when an [AngularMeteorObject](http://angular-meteor.com/api/AngularMeteorObject) is used as the "<formly-form model=" attribute.  Angular tries to do an angular.copy on it, I'd guess maybe to create an isolate scope for the formly directive.  Even if this worked, it would be a really bad thing to do - AngularMeteorObject is HUGE when all the references are chased - it wouldn't surprise me if it pulled in all of the relevant bits of the Mongo collection, connection, etc.

The workaround I use is simply the "Doctor, it hurts when I do that" solution - don't do that.  I don't need live updating from meteor, so I copy the fields from the AngularMeteorObject into a simple formly model object that just contains the fields, and then copy the fields back to do a save.  I have a simple utility function to do this that takes an array of field names.  

If there's anything to do to help this in formly, it might be to provide a copy utility function that traverses the "<formly-form fields=" fields object and does a deep copy of all the fields, given a source object and optional destination.  This may exist already - I didn't chase it.  I may write one later.

**Comment by kentcdodds** [comment] 2015-09-06 00:11
Take a look at formlyUtils.reverseDeepMerge

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)
