### ISSUE TITLE
Formly root-el="div" does not work as expected

### ISSUE THREAD

**Issue by koenweyn** [formly-js/angular-formly#328] opened 2015-06-02 09:14 UTC
As you can see here: http://jsbin.com/xohono/2, validation errors are not shown when formly like this:
```
<div ng-form="aForm">
  <formly-form root-el="div" form="aForm"></formly-form>
</div>
```
When you dive a little deeper, the field's scope does not contain a formControl, meaning that watchFormControl in formly-field.js doesn't work as expected.

**Comment by koenweyn** [comment] 2015-06-02 09:16
@kentcdodds can you confirm that the above code should work? I'll try to implement a unit test and fix if it should.

**Comment by kentcdodds** [comment] 2015-06-02 11:56
Fantastic catch @koenweyn. I'll have a fix for this asap. The problem is that because the root el isn't a `form` or `ng-form`, there is no `FormController` but angular-formly overrides it anyway. Actually, the way I'll fix it should resolve some issues that people have had in the past... I'll let you know when this is fixed. Thanks!

**Comment by kentcdodds** [comment] 2015-06-02 12:35
`$ npm install angular-formly@6.11.1` thanks!

**Closed** 2015-06-02 12:34 UTC
Labels: bug

**Comment by koenweyn** [comment] 2015-06-02 14:29
Hi @kentcdodds, the fix doesn't solve my issue.
When I run this testcase
```
  it(`should assign the scope's "form" property to the given FormController if it has a value`, () => {
    const el = compileAndDigest(`
      <form name="theForm">
        <formly-form model="model" fields="fields" form="theForm" id="my-formly-form" root-el="div"></formly-form>
      </form>
    `);
    const isolateScope = angular.element(el[0].querySelector('#my-formly-form')).isolateScope();
    expect(scope.theForm).to.eq(isolateScope.form);
    expect(scope.theForm.$name).to.eq('theForm');
  });
```
Formly emits this warning: 
```
'Formly Error: A formly-form does not have a `form` property. Many functions of the form (like validation) may not work. https://github.com/formly-js/angular-formly/blob/6.11.1/other/ERRORS_AND_WARNINGS.md#formly-form-has-no-formcontroller'
```
And when running my jsbin above, we can verify that validation is not working in this case.

**Comment by koenweyn** [comment] 2015-06-02 14:31
I think this testcase should be green (it's successful when not using root-el)
```
  it(`should put the formControl on the field's scope when using a different form root element`, () => {
    formlyConfig.setType({
      name: 'text',
      template: '<input name="{{id}}" ng-model="model[options.key]" />'
    });

    scope.fields = [
      {
        type: 'text',
        key: 'bla'
      }
    ];
    const el = compileAndDigest(`
      <form name="theForm">
        <formly-form model="model" fields="fields" form="theForm" id="my-formly-form" root-el="div"></formly-form>
      </form>
    `);

    const fieldScope = angular.element(el[0].querySelector('.formly-field')).isolateScope();
    expect(fieldScope.fc).to.exist;
  });
```

**Comment by kentcdodds** [comment] 2015-06-02 15:34
Thanks for the test! I pushed it out as 6.11.2
