### ISSUE TITLE
Chrome autofill - form field validation

### ISSUE THREAD

**Issue by mavrick** [formly-js/angular-formly#437] opened 2015-08-22 05:13 UTC
Hey,

Not sure if this has been discussed but I can't find anything on it. I am having form field validation issues with chrome autofill when someone chooses to remember their username and password for example on a login form. I've tried setting a $timeout(); with angular input change and blur events to hack around the issue but unable to fix 100%. 

Does anyone have any suggestions to work around this or even a potential fix moving forward?

Cheers

**Comment by kentcdodds** [comment] 2015-08-22 18:34
I'm not certain I understand what you mean, but if you want to completely workaround the autocomplete by Chrome, take a look at [the extras](http://docs.angular-formly.com/docs/formlyconfig#extras) for `formlyConfig`. Specifically the `removeChromeAutoComplete` property.

If that's not sufficient, could you please describe exactly what the problem is? Thanks.

**Comment by mavrick** [comment] 2015-08-22 23:27
Hey dude,

Cheers for the reply. The issue I am having is around form validation with input fields

I've got the `removeChromeAutoComplete`

```javascript
app.run(['formlyConfig', 'formlyApiCheck', function(formlyConfig, formlyApiCheck) 
{
  formlyConfig.disableWarnings = _config.env == "prod" ? true : false;
  formlyConfig.extras.removeChromeAutoComplete = true;
  formlyConfig.setWrapper({
    templateUrl: '/tpl/validators.html',
    types: ['input','checkbox','select','textarea','radio']
  });
}]);
```

```html
<form name="loginForm" ng-submit="handleLoginSubmit(model)">
  <formly-form model="model" fields="loginFields" options="options">
    <button type="submit" ng-disabled="loginForm.$invalid" class="btn btn-success btn-block text-uppercase">Sign In</button>
  </formly-form>
</form>
```

`loginForm.$invalid` is set to true on page refresh but the form is filled out by chrome:

![Sign In Button Disabled on page refresh](http://imgur.com/2oPAOOy.png)

My input fields are built with:

```javascript
$scope.loginFields = [
  {
    id: "dfragUsername",
    key: "username",
    type: "input",
    templateOptions: {
      required: true,
      focus: true,
      label: "",
      placeholder: "Username or Email Address"
    }
  },
  {
    id: "dfragPassword",
    key: "password",
    type: "input",
    templateOptions: {
      required: true,
      type: "password",
      label: "",
      placeholder: "Password"
    }
  }
];
```

Logging out the `loginForm` it is in an errored state until I focus on one of the fields or the signin button

*loginForm dump on page refresh:*

```json
{
  "$error": {
    "required": [
      {
        "$error": {
          "required": [
            {
              "$validators": {},
              "$asyncValidators": {},
              "$parsers": [],
              "$formatters": [
                null
              ],
              "$viewChangeListeners": [],
              "$untouched": true,
              "$touched": false,
              "$pristine": true,
              "$dirty": false,
              "$valid": false,
              "$invalid": true,
              "$error": {
                "required": true
              },
              "$name": "dfragPassword",
              "$options": null
            }
          ]
        },
        "$name": "formly_1",
        "$dirty": true,
        "$pristine": false,
        "$valid": false,
        "$invalid": true,
        "$submitted": false,
        "dfragUsername": {
          "$viewValue": "mavrick",
          "$modelValue": "mavrick",
          "$validators": {},
          "$asyncValidators": {},
          "$parsers": [],
          "$formatters": [
            null
          ],
          "$viewChangeListeners": [],
          "$untouched": false,
          "$touched": true,
          "$pristine": false,
          "$dirty": true,
          "$valid": true,
          "$invalid": false,
          "$error": {},
          "$name": "dfragUsername",
          "$options": null
        },
        "dfragPassword": {
          "$validators": {},
          "$asyncValidators": {},
          "$parsers": [],
          "$formatters": [
            null
          ],
          "$viewChangeListeners": [],
          "$untouched": true,
          "$touched": false,
          "$pristine": true,
          "$dirty": false,
          "$valid": false,
          "$invalid": true,
          "$error": {
            "required": true
          },
          "$name": "dfragPassword",
          "$options": null
        }
      }
    ]
  },
  "$name": "loginForm",
  "$dirty": true,
  "$pristine": false,
  "$valid": false,
  "$invalid": true,
  "$submitted": false,
  "formly_1": {
    "$error": {
      "required": [
        {
          "$validators": {},
          "$asyncValidators": {},
          "$parsers": [],
          "$formatters": [
            null
          ],
          "$viewChangeListeners": [],
          "$untouched": true,
          "$touched": false,
          "$pristine": true,
          "$dirty": false,
          "$valid": false,
          "$invalid": true,
          "$error": {
            "required": true
          },
          "$name": "dfragPassword",
          "$options": null
        }
      ]
    },
    "$name": "formly_1",
    "$dirty": true,
    "$pristine": false,
    "$valid": false,
    "$invalid": true,
    "$submitted": false,
    "dfragUsername": {
      "$viewValue": "mavrick",
      "$modelValue": "mavrick",
      "$validators": {},
      "$asyncValidators": {},
      "$parsers": [],
      "$formatters": [
        null
      ],
      "$viewChangeListeners": [],
      "$untouched": false,
      "$touched": true,
      "$pristine": false,
      "$dirty": true,
      "$valid": true,
      "$invalid": false,
      "$error": {},
      "$name": "dfragUsername",
      "$options": null
    },
    "dfragPassword": {
      "$validators": {},
      "$asyncValidators": {},
      "$parsers": [],
      "$formatters": [
        null
      ],
      "$viewChangeListeners": [],
      "$untouched": true,
      "$touched": false,
      "$pristine": true,
      "$dirty": false,
      "$valid": false,
      "$invalid": true,
      "$error": {
        "required": true
      },
      "$name": "dfragPassword",
      "$options": null
    }
  }
}
```

*Focus on any field or button:*

```json
{
  "$error": {},
  "$name": "loginForm",
  "$dirty": true,
  "$pristine": false,
  "$valid": true,
  "$invalid": false,
  "$submitted": false,
  "formly_1": {
    "$error": {},
    "$name": "formly_1",
    "$dirty": true,
    "$pristine": false,
    "$valid": true,
    "$invalid": false,
    "$submitted": false,
    "dfragUsername": {
      "$viewValue": "mavrick",
      "$modelValue": "mavrick",
      "$validators": {},
      "$asyncValidators": {},
      "$parsers": [],
      "$formatters": [
        null
      ],
      "$viewChangeListeners": [],
      "$untouched": false,
      "$touched": true,
      "$pristine": false,
      "$dirty": true,
      "$valid": true,
      "$invalid": false,
      "$error": {},
      "$name": "dfragUsername",
      "$options": null
    },
    "dfragPassword": {
      "$viewValue": "mavrick",
      "$modelValue": "mavrick",
      "$validators": {},
      "$asyncValidators": {},
      "$parsers": [],
      "$formatters": [
        null
      ],
      "$viewChangeListeners": [],
      "$untouched": true,
      "$touched": false,
      "$pristine": false,
      "$dirty": true,
      "$valid": true,
      "$invalid": false,
      "$error": {},
      "$name": "dfragPassword",
      "$options": null
    }
  }
}
```

**Comment by kentcdodds** [comment] 2015-08-26 15:51
Yeah, I don't think there's really anything that angular or angular-formly could do for you. If you have any specific ideas or fixes, I'm open to hearing them, but I'm going to go ahead and close this one as out of scope. Good luck!

**Closed by kentcdodds** 2015-08-26 15:51 UTC
