### ISSUE TITLE
datepicker gives an error

### ISSUE THREAD

**Issue by setakhero** [formly-js/angular-formly#427] opened 2015-08-13 18:49 UTC
Hi, 

I am new to angular-formly.

When I use datepicker as a field input, it gives an error like the following.

** Formly Error: There is no type by the name of "datepicker" **

Code snipet is exactely the same as the example.

    {
        key: 'date',
        type: 'datepicker',
        templateOptions: {
            label: 'Date',
            type: 'text',
            datepickerPopup: 'dd-MMMM-yyyy'
        }
    },

Any help?

Thanks.
Best,

**Comment by kentcdodds** [comment] 2015-08-13 18:57
Hi @setakhero, thanks for using angular-formly! The problem is that you need to define a `datepicker` type yourself. I recommend that you watch the videos here: http://learn.angular-formly.com to familiarize yourself with how angular-formly works.

The issues on this github repo are reserved for bug reports and feature requests. If you need help, please follow the instructions here: http://help.angular-formly.com. Good luck! I'm going to close this issue. See you in the chat! Thanks again.

**Closed by kentcdodds** 2015-08-13 18:57 UTC
