### ISSUE TITLE
Setting options.noFormControl on the fly

### ISSUE THREAD

**Issue by rbfinch** [formly-js/angular-formly#206] opened 2015-03-16 05:39 UTC
I'm trying to come up with a way to generate either an editable or read only version of a form depending on options passed to formly-form. I've modified field templates to display static field values when the read only form option is set. I have an example mostly working here: http://jsbin.com/ziwape/2/edit?output

`Formly Warning: Couldn't set the formControl after 2000ms` appears in the console when the form is initially displayed as read only since my template doesn't include anything with an ng-model attribute. I've tried to set `options.noFormControl` in the type's controller and in a templateManipulator (as I'm doing in the JS Bin example) but it seems to have no effect.  I'm guessing that noFormControl is being checked before the controller or templateManipulator is called.

Is there a way I can hook into something and set `options.noFormControl` on every field before the formly checks?  Or is there a better way to do this?

**Comment by kentcdodds** [comment] 2015-03-16 11:38
Terrific question. The problem is that the `options.formControl` gets set in the controller function which will only run once and then never again. The problem comes with the `ng-if` which rips the input field out of the DOM. If the field starts in the read only state then you'll get this warning because the field is not part of the form's `formControls`. If you set `noFormControl` then that will get rid of the warning, however the `options.formControl` will never be set and you wont be able to show validation errors, etc.

However! Angular will watch for when a new form control enters the DOM (when an ng-if evaluates to true and has an ng-model in it for example). So, what we can do is watch the form's property for the form control and add it to the scope/options ourselves! Yay!

Here's an updated working example :-) Let me know if there's anything else I can help you with!

http://jsbin.com/tinoxo/edit?html,js,output

**Comment by kentcdodds** [comment] 2015-03-16 11:42
By the way, I'm going to add this to our examples if that's ok with you. In the middle of making some updates to the website, but once that's done this will be part of the examples :-)

**Comment by kentcdodds** [comment] 2015-03-16 11:42
Closing this for now. Please feel free to reopen if I didn't answer your question :-)

**Closed by kentcdodds** 2015-03-16 11:42 UTC

**Comment by rbfinch** [comment] 2015-03-16 13:43
Awesome, thanks! Feel free to use that as an example.
