### ISSUE TITLE
Watchers not firing when fields are loaded lazily 

### ISSUE THREAD

**Issue by davincho** [formly-js/angular-formly#485] opened 2015-09-25 14:03 UTC
Demo: http://jsbin.com/liquniyali/1/edit?html,js,console,output

My code loads data asynchronously from the server (for example options for a <select>) so that the `fields` attribute of `angular-formly` will `be` updated after the data arrived from the server.
Angular-formly successfully renders the form, but does not fire any registered watchers/listeners.

**Comment by kentcdodds** [comment] 2015-09-25 16:35
I know what the problem is. When the form is rendered, angular-formly will look through the given fields and set up `$watch`ers with them. But angular-formly doesn't watch your fields after that point. So when you change them or anything, that initialization step doesn't run for those new fields.

One solution to this is to prevent the form from being rendered until the fields are available, like so: http://jsbin.com/fudufaj/edit?html,js,console,output

**Comment by kentcdodds** [comment] 2015-09-25 16:36
I'm going to go ahead and close this. If you need more help, please follow the instructions here: http://help.angular-formly.com

If this doesn't actually solve the problem, let me know. Thanks!

**Closed by kentcdodds** 2015-09-25 16:36 UTC
