### ISSUE TITLE
Using formly-skip-ng-model-attrs-manipulator to remove name attribute prevents formControl object from being populated

### ISSUE THREAD

**Issue by j--w** [formly-js/angular-formly#499] opened 2015-09-29 20:30 UTC
### JSBin Link
http://jsbin.com/naqaxo/edit?js,output

### Failing Test: formly-field.test.js
```
describe(`formly-skip-ng-model-attrs-manipulator`, () => {
  it(`should provide formControl when using formly-skip-ng-model-attrs-manipulator and no name is specified`, () => {
    scope.fields[0].template = `<input ng-model="model[options.key]" formly-skip-ng-model-attrs-manipulator />`;
    compileAndDigest();
    expect(field.formControl).to.exist;
  });
});
```

### Details
I am using formly for a credit card form that will be processed by a third party provider([Stripe.js](https://stripe.com/docs/tutorials/forms) or [Recurly.js](https://docs.recurly.com/js/#build-a-card-form)) both of these payment providers advise against using a **name** attribute on sensitive fields in case the form is accidentally submitted to the server(from error in JS failure for JS to preventDefault() or otherwise) as it prevents those sensitive fields from being posted to the server with the rest of the fields, getting stored in logs and voiding certain levels of PCI compliance.

I've gotten around this by using a custom field template that uses the **formly-skip-ng-model-attrs-manipulator** attribute and has no name attribute. The issue is that when I do this the options.formControl object seems to be dependent on the name attribute and is therefore not populated which means I don't get access to the validation helpers like **$valid**, **$pristine**.

Interested to hear your thoughts on if this is something you think formly should be able to handle.

**Comment by kentcdodds** [comment] 2015-09-29 20:35
This isn't an angular-formly issue, it's actually an angular issue. The problem is that without the `name` attribute, there's absolutely no way for me to get access to the `ng-model` controller. One thing you might consider is creating a directive which `require`s the `ngModel` controller and then attaches it to `scope.options`.

Give me a second and I think I could give you a quick example.

**Comment by kentcdodds** [comment] 2015-09-29 20:50
Here you go! http://jsbin.com/mebiju/edit?html,js,output


Because this isn't something that we'll be implementing in the core of angular-formly, I'll close this issue. However, if you like to make [a plugin](http://docs.angular-formly.com/page/plugins) for formly, that'd be way cool!

**Closed by kentcdodds** 2015-09-29 20:50 UTC

**Comment by j--w** [comment] 2015-09-29 21:17
It completely makes sense that it's an angular thing now that you mention it. Thanks for the JSBin, very helpful. I'll have a look at turning it into a plugin as I'll be neck deep in formly stuff at work for the next week or 2 i think.

**Comment by kentcdodds** [comment] 2015-09-29 21:31
Awesome! If you want a good kick-start on building an open source library, I recommend you checkout [my egghead.io series](https://egghead.io/series/how-to-write-an-open-source-javascript-library) :-)

**Comment by j--w** [comment] 2015-09-29 21:34
Oh I had actually just sent that link out to my team at work a couple of days ago, I didn't connect the dots that it was you who made them! I'll definitely be watching them, thanks for all your hard work!

**Comment by kentcdodds** [comment] 2015-09-29 21:41
:blush: yay!
