### ISSUE TITLE
Implementation with ui-select works but give error

### ISSUE THREAD

**Issue by estvmachine** [formly-js/angular-formly#595] opened 2016-01-07 15:15 UTC
Hi, i want to eliminate the error:
Error: [$compile:ctreq] Controller 'select', required by directive 'ngOptions', can't be found!

![image](https://cloud.githubusercontent.com/assets/2062668/12173936/8911b580-b538-11e5-93bc-a4df5d5320b3.png)

Who appears in the next example. The error you can read in the console.
http://jsbin.com/hakotah/8/edit?js,output

**Comment by benoror** [comment] 2016-01-07 17:03
Hi @estvmachine! Thanks for your interest in angular-formly. I'm sure that this issue is not mcaused by angular-formly.

I'm going to go ahead and close this issue because the github issues for this project are reserved for bug reports and feature requests. See you on chat! Thanks!

**Closed by benoror** 2016-01-07 17:03 UTC

**Comment by benoror** [comment] 2016-01-07 17:04
@estvmachine a google search gave me these related issues:

- https://github.com/mgcrea/angular-strap/issues/1473
- https://github.com/tamtakoe/oi.select/issues/10

Indeed downgrading to Angular 1.3 gets rid of the error:

- http://jsbin.com/nayoquduve/1/edit?html,js,console,output

Cheers!

**Comment by jasonwr** [comment] 2016-07-08 21:05
@benoror You do realize that [1473](https://github.com/mgcrea/angular-strap/issues/1473) just references back to this page. There really needs to be better support. Downgrading to Angular 1.3 isn't an option for everyone, especially those moving to 2.0. I'm upgrading a web app at work from 1.2 to 1.5 and it would be great to have an ng-options within a button.

**Comment by LeonSkrilec** [comment] 2016-07-22 15:48
Actually i got this error when placing ng-options on a non select DOM element. Might be helpful to someone debugging.

**Comment by hustshawn** [comment] 2016-09-05 08:43
Can someone tell how to fix it in using angular-formly?

**Comment by vamsikrishnamannem** [comment] 2017-01-21 19:05
I am also getting the same error.

**Comment by ViCe2099** [comment] 2017-06-30 10:29
When you are setting the field type you should not extend 'select', if you do so you will have this error.
