### ISSUE TITLE
hideExpression (and possibly asyncValidators?) don't fire when loading model asynchronously

### ISSUE THREAD

**Issue by SchizoDuckie** [formly-js/angular-formly#447] opened 2015-08-31 20:09 UTC
As you are aware, I've been working on loading my angular forms with JSON via my formly-loader service.

The frustrating part is that I cannot get (some?) of the expressions to work when the model is loaded asynchronously

As an example, I took your introduction sample plunkr and [brought it to plnkr](http://plnkr.co/edit/WXZQ39WEo2FqfyMuvxHK?p=preview) so that I could define a file and load it.

You'll notice that the why not field is not hidden, whereas in [this fork](http://plnkr.co/edit/dmQhXgi8HtgNkshWauSc?p=preview), where I define the form inline, everything works. As soon as you touch the 'why not' input, it hides. but as soon as you check and uncheck the checkbox and then type in the whyNot box the asyncValidator doesn't seem to be firing.

I decided to slim it down a bit to see if I could put my finger on what went wrong (and make sure that the template replacements weren't messing things up) and came up with this real-world minimal example:

Async example: http://plnkr.co/edit/f8ElJWBEQalTTFutGA8P?p=preview
Inline defined fork: http://plnkr.co/edit/YYYFRdYFFrniB4hs30FM?p=preview

Before I start digging through the formly-source and dive down the rabbit hole: is there anything simple I can do to force a digest or reapply so to say? (that's what it looks like to me)

**Comment by SchizoDuckie** [comment] 2015-09-01 19:26
update on this: I have found out that [when I define the model at the same time as the fields promise returns](http://plnkr.co/edit/ou2sn4gI7bOoXa07a5lD?p=preview), the first part of this problem is mitigated. The only thing that doesn't fire now are the watchersthat are defined via expressionProperties.
 
@kentcdodds any ideas?

**Comment by kentcdodds** [comment] 2015-09-04 15:30
I'm sorry I've been so silent on this. I haven't had a chance to give it a good look. Sorry! :-/ I'll try to give it a closer look soon!

**Comment by SchizoDuckie** [comment] 2015-09-04 16:17
Not a problem man, you're busy juggling 2 frameworks, 3 personal projects and then doing all the videos. And I thought *I* was busy :shipit:

**Comment by kentcdodds** [comment] 2015-09-04 16:18
Haha, and I have a day job :P thanks for understanding :-)

**Comment by SchizoDuckie** [comment] 2015-09-04 16:20
Same here :+1: plus, this is probably not a fun one to investigate.

If I can do anything to help clarify the problem, just shout.

**Comment by kentcdodds** [comment] 2015-09-08 12:38
Finally getting a chance to look into this. And I don't think I'm seeing the problem that you are... Do you mind trimming the example down a little bit and giving step-by-step reproduction instructions?

**Comment by kentcdodds** [comment] 2015-09-21 01:51
ping?

**Comment by SchizoDuckie** [comment] 2015-09-21 11:39
Oh hey, completely missed this notification. I will try to give you a more detailed example tonight!

**Comment by SchizoDuckie** [comment] 2015-09-21 21:12
So, some more detailed reproduce steps, I hope this clarifies some things. I didn't have time tonight to further trim the example, sorry for that, if you still need me to just shout.

- load http://plnkr.co/edit/ou2sn4gI7bOoXa07a5lD?p=preview
- uncheck the 'awesome' checkbox
- Type in the textarea
- observe that the watcher is not firing, not triggering the default behavior of blocking the typing into 'whyNot'.
- expresionProperties *are* firing (see console.log) because I define both vm.model and vm.fields at the same time (see script.js line 64), after the JSON is loaded and pre-parsed. When vm.model is defined first and vm.fields is loaded async, expressionProperties do not work.

**Comment by kentcdodds** [comment] 2015-09-25 16:45
I realized what the problem was when I saw #485. The solution is the same: http://plnkr.co/edit/0roe4DzhhkANhOdJxhoX?p=preview

**Comment by kentcdodds** [comment] 2015-09-25 16:45
I'm going to close this. Let me know if you need more help

**Closed by kentcdodds** 2015-09-25 16:45 UTC
Labels: needs investigation, waiting to hear back

**Comment by SchizoDuckie** [comment] 2015-10-03 00:01
Thanks man! I've fixed this indeed by defining both my vm.model and vm.fields only after my JSON loader has finished loading and preparsing the JSON, ergo, in the .then() for the .load() :shipit: 

```
FormlyLoader.load('CustomSearchEngine').then(function(fields) {
    if (data.engine && !data.isNew) {
        pageLog("Engine detected that isn't new, editing mode");
        self.model = data.engine;
    } else if (data.isNew) {
        pageLog("New engine detected, adding mode");
        self.model = {};
    }
    self.fields = fields;
});
```

![image](https://cloud.githubusercontent.com/assets/111710/10260182/5c2b290a-6972-11e5-97f4-3c9cfe378ad9.png)

**Comment by kentcdodds** [comment] 2015-10-03 04:22
Fantastic! Sorry it took so long for me to respond.

**Comment by SchizoDuckie** [comment] 2015-10-03 08:58
No sweat! You have a new baby and I've been swamped myself too!
