### ISSUE TITLE
FormlyConfigProvider content length question

### ISSUE THREAD

**Issue by icfantv** [formly-js/angular-formly#387] opened 2015-07-12 02:18 UTC
Just a clarification:  If I require lots of different custom formly templates, am I just doing it wrong or is it customary to have a `.config` function where one makes a bunch of calls to `formlyConfigProvider` to set wrappers and types?

I recall you mentioning at ng-conf that you yourself almost always use custom templates.  If loads of different types and wrappers are ok, is there a way you would recommending structuring the `.config` so that it doesn't get out of control?

**Comment by kentcdodds** [comment] 2015-07-12 02:49
Good question. In my app, I have probably 20 different types and a handful
of template manipulators. Each gets its own file and therefore its own
config function. This makes things quite manageable. Let me know if you
have questions :-)

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment] 2015-07-12 02:49
I'm going to go ahead and close this because it's not a bug out feature request. But feel free to respond if you have further questions.

**Closed by kentcdodds** 2015-07-12 02:49 UTC

**Comment by icfantv** [comment] 2015-07-12 03:03
That makes absolute sense.  When you say separate file, you mean template HTML file, right?  I like the idea of separate `.config` calls - I'm going to break mine apart.  And yes, totally cool closing this.  Thanks.

**Comment by kentcdodds** [comment] 2015-07-12 03:31
Both separate html files as well as js files and css files and test files.
I consider each type to be its own unit.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)
