### ISSUE TITLE
form starts with valid state even if it contains fields with not valid default values

### ISSUE THREAD

**Issue by cdbizone** [formly-js/angular-formly#221] opened 2015-04-01 10:04 UTC

**Comment by kentcdodds** [comment] 2015-04-01 12:14
If I understand your issue correctly, this is by design. If you wish it to show errors, you can set `validation.show` to true, like so: http://angular-formly.com/#/example/other/force-show-error

**Comment by kentcdodds** [comment] 2015-04-01 12:15
I'm going to close this now. Please re-open it if this doesn't solve your issue or if you have further questions.

**Closed by kentcdodds** 2015-04-01 12:15 UTC

**Comment by cdbizone** [comment] 2015-04-01 21:35
http://jsbin.com/fohifojoso/2/edit?html,console

**Comment by kentcdodds** [comment] 2015-04-01 21:38
I'm sorry @cdbizone. I really have no idea what your issue is... Please be more specific about the issue that you're experiencing. From what I can tell, everything is working as designed...

**Comment by cdbizone** [comment] 2015-04-01 21:40
for example if we have an iframe that should be rendered only if form has valid state and src attr depends on form field values, it starts to load iframe with incorect src (catch this bug in firefox)

**Comment by cdbizone** [comment] 2015-04-01 21:41
we need some posibility to find out that all inputs have been added to form

**Comment by kentcdodds** [comment] 2015-04-01 21:54
Oh, so if you can hide the iframe based on the `$valid` property of the form. This is similar to how you would [disable a submit button](http://angular-formly.com/#/example/other/disable-submit-button) (except you'd use `ng-if` instead of `ng-disable`). Does that answer your question?

**Comment by cdbizone** [comment] 2015-04-01 21:55
we have next workflow: 
angular finds tag form. He said. Ok! I know this directive. there is no input with ng-model attr inside of it so i marked it as valid, than formly-form starts to interact. Hold on man, there are some inputs in this form  , they have some validation that you should know about it. Oh ok, now i see form is invalid.

With the static form we haven't this issue

**Comment by kentcdodds** [comment] 2015-04-02 02:22
Ok, I understand what you're talking about now. So this is what I would do: http://jsbin.com/fivuqa/edit
