### ISSUE TITLE
Sorting Fields

### ISSUE THREAD

**Issue by andyfensham** [formly-js/angular-formly#230] opened 2015-04-07 09:04 UTC
I am changing the field order of "fields="newForm".  In the console I can see the field order changed, but formly does not change the field order.  How can I get formly to refresh the fields based on the new order.

    <formly-form model="newFormData" fields="newForm">
                <button ng-hide="newForm.length==0" type="button" class="btn btn-default" ng-    click="onSubmit()">Submit</button>
            </formly-form>

Thanks

**Comment by kentcdodds** [comment] 2015-04-07 12:57
angular-formly does a lot of stuff to render your fields and it doesn't to great when you modify the fields after the initial compile (as @ValentinH has discovered as well). I'm starting to think that modifying fields order/entirely after compile may be something I need to look at supporting better.

For now though, perhaps you could describe what you're trying to accomplish and I can give you a useful work around.

**Comment by andyfensham** [comment] 2015-04-07 13:25
Hi Kent,

Maybe you can just supply a parameter on the form that would recompile/refresh.  I am creating a drag-drop form designer where people can change the form on the fly.  They can change the label, placeholder, key, description etc.

Thanks

Andy

**Comment by kentcdodds** [comment] 2015-04-07 13:27
That sounds awesome! Would you like to [build this](https://github.com/formly-js/formly-builder/issues/1)? I would totally love that!

For your case, I think you may just want to recompile things every time you change something. Take a look at [kcd-recompile](http://kent.doddsfamily.us/kcd-angular/#/kcd-recompile)

**Comment by kentcdodds** [comment] 2015-04-07 13:28
The problem is that some templates use singly bound expressions (like `::to.label`) for example. So with those, you HAVE to recompile the entire template. So kcd-recompile should help you with that.

**Comment by andyfensham** [comment] 2015-04-07 14:03
Hi Kent..

How would I use with formly.  Would I just put 

    <formly-form kcd-recompile model="newFormData" fields="newFormClone">
                    <button ng-hide="newForm.length==0" type="button" class="btn btn-default" ng-    click="onSubmit()">Submit</button>
                </formly-form>

Thanks

Andy

**Comment by kentcdodds** [comment] 2015-04-07 14:16
I would do something like:

```html
<div kcd-recompile="newFormClone">
  <formly-form model="newFormData" fields="newFormClone">
    <button ng-hide="newForm.length==0" type="button" class="btn btn-default" ng-    click="onSubmit()">Submit</button>
  </formly-form>
</div>
```

Then I would alter `kcd-recompile` to use a deep watch.

```js
angular.module('kcd.directives').directive('kcdRecompile', function($compile, $parse) {
  'use strict';
  return {
    scope: true, // required to be able to clear watchers safely
    compile: function(el) {
      var template = getElementAsHtml(el);
      return function link(scope, $el, attrs) {
        var stopWatching = scope.$parent.$watch(attrs.kcdRecompile, function(_new, _old) {
          var useBoolean = attrs.hasOwnProperty('useBoolean');
          if ((useBoolean && (!_new || _new === 'false')) || (!useBoolean && (!_new || _new === _old))) {
            return;
          }
          // reset kcdRecompile to false if we're using a boolean
          if (useBoolean) {
            $parse(attrs.kcdRecompile).assign(scope.$parent, false);
          }

          // recompile
          var newEl = $compile(template)(scope.$parent);
          $el.replaceWith(newEl);

          // Destroy old scope, reassign new scope.
          stopWatching();
          scope.$destroy();
        }, true); // <-- that
      };
    }
  };

  function getElementAsHtml(el) {
    return angular.element('<a></a>').append(el.clone()).html();
  }
});
```

**Comment by andyfensham** [comment] 2015-04-07 14:24
Thanks..Will try it.  I am new to Angular..not sure whether I will be able to build it in.  Will give it a try and ask you if I get stuck.

Tnx

**Comment by kentcdodds** [comment] 2015-04-24 12:32
This worked "like a charm" for @joezhouOxford in #246 https://github.com/formly-js/angular-formly/issues/246#issuecomment-95852663 so I'm going to close this issue.

**Closed by kentcdodds** 2015-04-24 12:32 UTC
Labels: waiting to hear back

**Comment by SagiMedina** [comment] 2015-04-27 14:05
@kentcdodds great workaround!
For those who follow John Papa style guide:
```
(function () {
    'use strict';

    angular
        .module('kcd.directives') // change or inject it
        .directive('kcdRecompile', kcdRecompile);

    kcdRecompile.$inject = ['$compile', '$parse'];

    function kcdRecompile($compile, $parse) {

        var directive = {
            scope: true,
            compile: compile
        };
        return directive;

        function compile(element, attrs) {
            var template = getElementAsHtml(element);

            return function link(scope, element, attrs) {
                var stopWatching = scope.$parent.$watch(attrs.kcdRecompile, function(_new, _old) {
                    var useBoolean = attrs.hasOwnProperty('useBoolean');
                    if ((useBoolean && (!_new || _new === 'false')) || (!useBoolean && (!_new || _new === _old))) {
                        return;
                    }
                    // reset kcdRecompile to false if we're using a boolean
                    if (useBoolean) {
                        $parse(attrs.kcdRecompile).assign(scope.$parent, false);
                    }

                    // recompile
                    var newEl = $compile(template)(scope.$parent);
                    element.replaceWith(newEl);

                    // Destroy old scope, reassign new scope.
                    stopWatching();
                    scope.$destroy();
                }, true); // <-- that
            }
        }

        function getElementAsHtml(element) {
            return angular.element('<a></a>').append(element.clone()).html();
        }
    }
})();
```

Keep in mind that you need change the html too since you are using controllerAs syntax:

```
<div ng-controller="worker as workerCtrl" kcd-recompile="workerCtrl.formFields">
   <formly-form model="workerCtrl.worker" fields="workerCtrl.formFields" options="workerCtrl.formOptions">
   </formly-form>
</div>
```

**Comment by astanciu** [comment] 2015-12-08 16:16
This works great, except that fields with default validations cause a reset. For ex, a type:email field using the boostrap templates, as soon as you blur the field leaving an invalid email, it clears the value (assuming form re-compilation happens)

**Comment by vodich** [comment] 2016-07-12 23:02
This causes my chrome to eat a ton of memory :) I have uib-tabs that have a directive inside, that listens to event that updates the data from another directive and too many watchers are taking their toll I guess :(
