### ISSUE TITLE
Improve performance with many fields

### ISSUE THREAD

**Issue by rtrompier** [formly-js/angular-formly#259] opened 2015-04-21 09:14 UTC
Hi,
Is it possible to know when formly has loaded all the fields ? 
Because on big form, we can see the fields created one by one.
We would like to add a loader during a render.
Thx

**Comment by XciD** [comment] 2015-04-21 09:25
+1

**Comment by kentcdodds** [comment] 2015-04-21 11:54
So, I think the better solution would be to make this render faster. If you look at `ng-stats` with `logDigest` turned on, you'll see that when you render a form, there are a TON of digests that run. We need to figure out why that is and see if we can make it so only one digest runs. This is high on my priority list because the initial compile of the form fields is just really terrible and needs improving. I'll keep you informed of my progress.

**Comment by XciD** [comment] 2015-04-21 13:32
Thanks for you answer. 

I can provide you on private a peace of our code where you can see this appending.

We are also using ocLazyLoad to load template dependency (like select2 or datatable) on the fly so an state variable on each Form could be nice, we can put an loader during the process..

**Comment by kentcdodds** [comment] 2015-04-21 13:35
That wont be necessary... I have a pretty good working example locally that I'm working though. I think the main trouble is simply the way angular works... But I'm confident that we can find a work around to make this much faster.

**Comment by kentcdodds** [comment] 2015-04-21 14:53
First off, I should say that I'm not going to implement the original question. Not only is it the incorrect way to go about solving the problem, it's also pretty much impossible without some bad hackery against angular.

Secondly, if anyone wants to contribute to this at all, see [this branch](https://github.com/formly-js/angular-formly/tree/throw-away/fast) where I've started trying to setup some kind of benchmark to test out how to make it faster. Again, I think that it's just an angular problem... Need to figure out a good workaround...

**Comment by XciD** [comment] 2015-04-25 09:12
I understand perfectly, nevertheless we are quite ready to go live with our product and it's one of our "biggest" problem, It's not very "sexy" for users when they display the form.

I will try to understand your code in order to implement this temporary fix :)

**Comment by kentcdodds** [comment] 2015-04-25 12:31
By the way. If you would like to be notified when all fields have finished loading, then you *could* implement something that would probably work by adding a custom `link` function to all your fields by creating a custom `type` that all of your other field types `extend`. Then in that `link` function, you have access to the field `scope` which has an `options` property for the specific field and a `fields` property for all the fields of the form. Set something on the `options.data` property to say that the specific field has been loaded, then iterate through the `fields` to see if all of the fields have had that property set. If they have, then fire an event.

As I said, this is a terrible way to go about this. Also, the UI thread is still going to be tied up with angular's digest cycle (so users will likely notice that), but it at least gets you what was originally requested...

**Comment by XciD** [comment] 2015-04-27 13:33
Thanks for your answer.

We just found that if we remove template that works with [ocLazyLoad](https://github.com/ocombe/ocLazyLoad) the form render faster and enough quick for us.

We had some directive with ocLazyLoad to load dependencies on the fly like select2 or datepicker, and they trigger the link function before rendering on front. 

We fix this by loading all our component in the resolve of the route... Not the best solution.

I think you should consider to implementing a state variable to the Formly directive.

**Comment by kentcdodds** [comment] 2015-04-28 03:30
I'm not sure what you mean by that last bit there...

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment] 2015-04-30 14:56
Changing the name of this to resemble what the solution will be. Also, if anyone wants to take a whack at a solution, I've created [this example](http://jsbin.com/kudixe/edit) which demonstrates where formly falls over (though, to be honest, I think it's more of an angular problem than a formly problem).

**Comment by pedrocatre** [comment] 2015-05-04 13:34
+1
Improvements on this would be great. I have a form that in the worst case can have over 100 fields on the page. Not only does it look bad because it takes time to show them all, it can also become quite slow.

**Comment by kentcdodds** [comment] 2015-05-04 14:36
@pedrocatre, take a look at using [ng-stats](https://github.com/kentcdodds/ng-stats) to do a quick manual benchmark of the performance of your page with > 100 fields. The idea behind formly is that you only pay for watchers that you absolutely need. So, even though it takes angular a while to compile the template in the first place, you should end up with the fastest possible output for forms using angular.

It is my expectation that you can't build a faster form with angular even if you hard-coded the HTML it produces. I have never tested this though. I do expect that a hard-coded version would be *marginally* faster, but not enough to justify not using angular-formly. I would love it if someone verified my expectation. If it turned out incorrect, it would give me hope that there's something formly can do to speed things up.

**Comment by pedrocatre** [comment] 2015-05-04 14:50
I will check it out. Thanks.

The thing is it is possible that a "hard coded" traditional angular form would still be slow with so many fields being shown. But I do need to investigate this further. When all of the form fields groups are hidden except for one I still get a slow form for safari and ie9.

I basically used ng-options so the models only update on blur and this made things much much better for the worst step of the form. But I did not think I would have to do this.

**Comment by kentcdodds** [comment] 2015-05-04 15:09
Note, you can use `ng-model-options` with formly using the `modelOptions` property.

**Comment by cnaccio** [comment] 2015-05-14 19:44
I'm currently experiencing a huge performance problem using angular-formly with a form fields array containing 1300 items (form fields, templates, classNames, etc...). My development machine is pretty beefy (32GB memory, SSD, Intel i7 3.5GHz quad core), but when I update the formFields array that the angular-formly directive is configured to use my browser slows to a crawl. What's interesting is that after a couple minutes things are back to normal, and I can scroll through this huge form while performance remains snappy. However if I attempt to edit any of the fields by changing a value to slowness starts again. Any advice would be much appreciated.

**Comment by pedrocatre** [comment] 2015-05-14 19:51
You can use ng-model options so that the value only updates on blur or after several milliseconds.
You can also try to remove the number o bindings in your templates (for example: I would have liked to have bindings to change the classes on the form so I can customise it to different uses but I can live without all that. Finally use one time binding for everything that can be one time binded.

Additionally you could divide the form into steps (there is an example of using angular form with a multistep wizard) so that you don't have all the watchers for the form active at the same time. The wizard being used in the example uses ng-show and you don't want this though. But it is simple enough to go into the source code and change it to use ng-if. Hope this helps.

**Comment by kentcdodds** [comment] 2015-05-14 19:53
Hoping to work on this soon. I have s lead that looks promising...

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by cnaccio** [comment] 2015-05-14 20:11
Here's a jsbin I setup for demonstrate the exact trouble I'm having.

http://jsbin.com/yeticelepa/3/edit?html,js,output

**Comment by kentcdodds** [comment] 2015-05-14 20:28
I think that the problem may be the promise chaining in the `link` function of a `formly-field`: https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L187

I believe it's because on every `resolve`, there's a `$digest` due to the `$q` library. I reached out [on twitter](https://twitter.com/kentcdodds/status/598924680938921984) and got a few tips that lead me to develop these different examples

Current: http://jsbin.com/kudixe/edit 
$$q: http://jsbin.com/fikeku/edit 
Native Promise: http://jsbin.com/pizizi/edit 

Unfortunately, I don't think that these are making a difference currently. I welcome anyone to try variations of this and try to figure out how to fix the problem...

To try something out:

- Checkout the repo
- `$ npm install`
- Make your changes (it's ES6)
- `$ npm run build` (don't bother with tests, we can fix those later)
- Create a github gist out of the resulting `dist/formly.js`
- Use http://rawgit.com/ to get a url to your gist
- Clone [this template](http://jsbin.com/kudixe/edit)
- Replace the `formly.js` file with your rawgit URL.

Did it work? I hope so!

If you want to try a few things out and have a better workflow, try this:

- `$ npm run watch`
- `$ http-server dist` [http-server](https://www.npmjs.com/package/http-server)
- `$ ngrok 8080` [ngrok](https://ngrok.com/)
- Replace the rawgit URL with your ngrok url
- Make changes, refresh your jsbin.

I appreciate anyone who wants to help out with this!

**Comment by kentcdodds** [comment] 2015-05-14 20:31
By the way @cnaccio, that's a LOT of fields... I don't know if you'd get good enough performance doing it by hand with just angular...

**Comment by cnaccio** [comment] 2015-05-14 21:52
Lol I figured that much. I'm trying to figure out a better solution... Maybe something like instead of rending a form simply render a view where I can click on a field to make it editable instead of assuming every field needs to be editable. Any advice on using formly with x-editable?

**Comment by kentcdodds** [comment] 2015-05-14 22:02
you might look into the [read-only](http://angular-formly.com/#/example/other/read-only-form) example. Never used x-editable myself...

**Comment by kentcdodds** [comment] 2015-05-14 22:03
Hmmm, looking at x-editable, I don't think that the read-only example will really do it for you... I would probably just create a directive that integrates with x-editable, then create a custom type with a template that uses this directive.

**Comment by SomeKittens** [comment] 2015-05-15 01:48
Specifically, `$q` runs `$evalAsync` which means that while it's not a 1:1 $q:$digest, it's about 70-80% when the promises resolve in 0 < x < 1000ms.

JSBin with details: http://jsbin.com/sarabifuni/1/edit?html,js,output

**Comment by jvandemo** [comment] 2015-05-15 03:48
I have created a plnkr here with the current master version of formly:

http://plnkr.co/edit/wPKCKVGiR99wEUZFalp0?p=preview

Now you can edit `formly.js` directly in Plnkr without having to install/build anything locally (for those interested in helping troubleshoot).

**Comment by jvandemo** [comment] 2015-05-15 03:52
Update: enabling apply async:

```javascript
app.config(function ($httpProvider) {
  $httpProvider.useApplyAsync(true);
});
```

does not make a difference in this example, probably because the templates are already loaded in the cache.

**Comment by jvandemo** [comment] 2015-05-15 03:54
@kentcdodds &mdash; I have added a `$timout` around `getFieldTemplate()` on line 1137 in http://plnkr.co/edit/Ab0A2k1can4fyY4g3b6H?p=preview

This pushes the logic to the next tick and speeds up rendering a lot. However, my knowledge of formly is not good enough to judge what the impact is on its inner workings.

If you open up the log, you will see that the fields render quickly and then the promises are resolved in the background while the fields are already displayed.

**Comment by kentcdodds** [comment] 2015-05-15 04:51
@jvandemo, wow! Thanks for setting up the plunkr and the improved example with a setTimeout/$timeout. Unfortunately, I tried it out in my app and it's hard to describe but the user can visually see things getting rendered which isn't very pretty. Kind of a toss-up which is a better experience.

**Comment by kentcdodds** [comment] 2015-05-15 04:53
I should also mention, there's one place in particular where performance in my app is not so good due to a lot of fields being rendered. @paulirish helped me interpret some Chrome profiling output for it. Perhaps this will be useful to anyone trying to help speed up angular-formly: https://docs.google.com/document/d/1QSkfqoiZS203BG5hTELTt1GvyD1qc9rDXOpMym9IKlw/edit?usp=sharing

**Comment by kentcdodds** [comment] 2015-05-15 04:54
Also, I just want to say thank you to anyone helping on behalf of the many developers using angular-formly. Most developers wont come up against these perf issues, but for those of us trying to display many fields, this is definitely a problem. So thanks to anyone who puts time and effort into improving the performance of angular-formly.

**Comment by kentcdodds** [comment] 2015-05-15 04:56
One thing that I've toyed around with is perhaps compiling everything from the `<formly-form>` element down manually and then inserting it into the DOM after all the field templates have been resolved. I'm a little sceptical that this would really improve performance though. Just a thought.

**Comment by jvandemo** [comment] 2015-05-15 04:58
> Thanks for setting up the plunkr and the improved example with a setTimeout/$timeout. Unfortunately, I tried it out in my app and it's hard to describe but the user can visually see things getting rendered which isn't very pretty. Kind of a toss-up which is a better experience.

@kentcdodds &mdash; instead of wrapping the `$timeout` around the entire `getFieldTemplate` call, you can also use it inside one of the chained actions that you think is causing the slowdown. So it would e.g. immediately perform the first 3 actions and then send the last 3 actions to the next tick.

Unfortunately I'm not familiar with the inner workings of formly. I can try a few variations but you may have better insights in which parts of the chain need to be performed immediately to prevent rendering issues.

I will set up a few experiments to see if I can figure it out...

**Comment by jvandemo** [comment] 2015-05-15 05:08
Here's a screenshot of a timeline and CPU profile using 1000 fields and the original formly from master:

![timeline](https://cloud.githubusercontent.com/assets/1859381/7647209/12f13816-fad1-11e4-85ca-b624b9e7e9db.png)

![digest](https://cloud.githubusercontent.com/assets/1859381/7647194/bf5dbe36-fad0-11e4-98fa-b123a2e67301.png)

Looks like digest is eating up all CPU and causing the delays, not DOM rendering.

**Comment by kentcdodds** [comment] 2015-05-15 05:08
@jvandemo, for the benefit of those watching at home, [this is the code](https://github.com/formly-js/angular-formly/blob/master/src/directives/formly-field.js#L187-L201) that we're talking about. I believe that this is the bottleneck of the render. It's inside of the `formly-field` directive's `link` function.

Here it is with annotations

```javascript
getFieldTemplate(scope.options) // <-- get the template for the field based on it's template/templateUrl or it's type's template/templateUrl
  .then(runManipulators(formlyConfig.templateManipulators.preWrapper)) // <-- run the preWrapper templateManipulators. This is an array of functions that can return a (modified or unmodified) template string, element, or a promise which resolves to one of these things. We $q.all a $q.when of each of them
  .then(transcludeInWrappers(scope.options)) // <-- this will "transclude" (but not really) the template into any of its own or it's type's wrappers, similar in function to a template manipulator
  .then(runManipulators(formlyConfig.templateManipulators.postWrapper)) // <-- like the preWrapper manipulators, just another place to put manipulators in the pipeline for maximum flexibility
  .then(setElementTemplate) // <-- this is where the template is finally $compiled and inserted into the DOM
  .then(watchFormControl) // <-- this is where we set up a watcher to add the NgModelController to the options. I would be very surprised if this was part of the problem in itself.
  .then(callLinkFunctions) // <-- this is where we call the field's link function and its type's link function (and any link functions that type extends).
  .catch(error => {
    formlyWarn(
      'there-was-a-problem-setting-the-template-for-this-field',
      'There was a problem setting the template for this field ',
      scope.options,
      error
    );
  });
```

**Comment by kentcdodds** [comment] 2015-05-15 05:16
Tried commenting out the templateManipulators and wrappers and it made a marginal difference [in the plunk](http://plnkr.co/edit/9hLpoPeKCcEOXUCRtyI1?p=preview) but pretty much no difference in my app...

**Comment by kentcdodds** [comment] 2015-05-15 05:18
I feel like if there were a way to tell angular to pause digests for just a moment while this thing compiled, that would improve things. But that may just be me misunderstanding how compiling things works. Maybe @teropa could provide some insight there?

**Comment by jvandemo** [comment] 2015-05-15 05:19
@kentcdodds &mdash; I have added some code to hide the field until it the end of the chain has been reached: http://plnkr.co/edit/37gE36pW5PIF6osCUVCB?p=preview (see line 1151 in formly.js).

This should take care of hiding the field until it's promise has been resolved in the background.

**Comment by kentcdodds** [comment] 2015-05-15 05:23
Yeah, I looked at that too. Unfortunately, you can still see the fields getting rendered one-by-one and suddenly appearing. I really want to find a solution where it's all suddenly rendered immediately. I just hope this is something that's possible with angular... Starting to wonder if perhaps changing this to not use promises would improve the situation... Unfortunately, the async api is one of the things that makes angular-formly so consumable.

**Comment by kentcdodds** [comment] 2015-05-15 05:24
Toyed around with the idea of having two different link functions and using one or the other based on some pre-configured preference. Most developers wont run into this, but if you do, then you may be willing to give up the niceties of the async api for improved performance (if that's what we'd really get by removing the async api...)

**Comment by jvandemo** [comment] 2015-05-15 05:26
> I feel like if there were a way to tell angular to pause digests for just a moment while this thing compiled, that would improve things. But that may just be me misunderstanding how compiling things works. 

@kentcdodds &mdash; It's not the compilation causing the problem here. You are resolving promises inside the link function, so you will always have to resolve `n` promises for `n` elements.

What you can do is write code to queue promises and then call a digest after a certain timeout. So instead of resolving the promise in the link function, you would then send the promise to the queue.

The queue could be managed by a service or a controller in a surrounding directive.

Then it would be a bit similar to how `$httpProvider.useApplyAsync()` works.

**Comment by kentcdodds** [comment] 2015-05-15 05:32
I think I understand what we think the problem is. You're suggesting that the problem is that a `$digest` is being called for every promise for every field (which can be huge as a single field could have as many as 10 or more promises). That's what you're suggesting, correct? I think that's what it is as well...

What I don't understand is how putting those promises into a queue outside of the link function will prevent a `$digest` from being called after they are each resolved. The only thing I could think of to avoid that was to either use `$$q` or the native `Promise` (or a polyfill) and trying those didn't seem to make a difference.

I think I may just be misunderstanding though.

**Comment by kentcooper** [comment] 2015-05-15 05:33
Just to add a different perspective to this. I currently do something similar to formly except I use the server to basically render a raw angular form and past about 200 inputs just compiling the HTML takes a significant amount of time. I did a couple of benchmarks using 200 fields in formly and 200 straight angular fields and the performance difference is not very noticeable.

**Comment by kentcdodds** [comment] 2015-05-15 05:35
Thanks @kentcooper (awesome name by the way). I've been wanting to benchmark this against doing angular forms by hand (without formly) to see if formly is any worse than regular forms. I always believed strongly that it wasn't much worse, but never had any evidence or tested the theory.

To be perfectly honest, based on what @kentcooper has said, I'm doubtful that we can improve the performance without doing some serious hackery-trickery with angular... It's not a formly problem, it's an angular problem...

**Comment by kentcooper** [comment] 2015-05-15 05:42
It seemed that way to me. I could try running a different number of fields though. I wasn't sure at what number of fields the slow down was occurring in formly so I just based it on a form I already had created.

**Comment by jvandemo** [comment] 2015-05-15 05:53
> What I don't understand is how putting those promises into a queue outside of the link function will prevent a $digest from being called after they are each resolved. The only thing I could think of to avoid that was to either use $$q or the native Promise (or a polyfill) and trying those didn't seem to make a difference.

Using native promises you can prevent Angular from doing a digest for every single promise (since it's happening outside the Angular world) and then perform a manual digest after a set amount of time.

This reduces the number of digest cycles. However, it will only speed things up if it is the digest cycle that is actually causing the problem since the amount of logic (to resolve the promises) remains the same.

A normal timeline using $q:

```
- resolve promise
- digest
- resolve promise
- digest
- resolve promise
- digest
- resolve promise
- digest
- ...
```

When using a queued approach (using promises that don't trigger digest cycle automatically):

```
- resolve promise
- resolve promise
- resolve promise
- resolve promise
- digest
- ...
```

So if the digest cycle is causing the slowness, it will help since there are less digest cycles.

If it is the logic to resolve the promises, this will not provide any benefits, since there is an equal amount of logic to perform.

Hope that helps!

**Comment by jvandemo** [comment] 2015-05-15 06:14
Quick update: just noticed that you use `$http.get` in `getTemplate`.

Since `$httpProvider.useApplyAsync(true)` does not cause significant speed improvements, building your own queue will probably not provide any benefits either, unless you could make the interval a bit larger (I believe it is around 10ms with useApplyAsync).

I'll see if I can add some timers to find out if it would help...

**Comment by gdi2290** [comment] 2015-05-15 06:19
I used $$q and got it working the way that everyone wanted

**Comment by jvandemo** [comment] 2015-05-15 06:24
@gdi2290 &mdash; Sounds awesome! Is it available online?

**Comment by jvandemo** [comment] 2015-05-15 06:28
I have created a plnkr that shows the milliseconds for every promise chain: http://plnkr.co/edit/fbbs2aHsPcLof3ENQnml?p=preview

![chains](https://cloud.githubusercontent.com/assets/1859381/7647880/f8f75a7a-fadb-11e4-8431-635ab8fa888c.png)

- each promise chain takes about 5ms on average on my macbook
- `useApplyAsync` queues for about 10ms so that explains why it doesn't help much

**Comment by gdi2290** [comment] 2015-05-15 06:28
@jvandemo yeah http://plnkr.co/sex06c

**Comment by jvandemo** [comment] 2015-05-15 06:39
@kentcdodds &mdash; From what I can see so far it takes the promise chain 5ms on average (see screenshot in previous comment) to complete.

So it will take on average:

- 100ms to process form with 20 fields
- 500ms to process form with 100 fields
- 5000ms to process form with 1000 fields

So no matter what actions you take outside of the promise chain, these numbers are always going to be the minimum time needed to process the form unless you start changing the promise chain itself.

If you're interested in optimizing the chain itself, we can add timers for each function in the chain to see what is taking most time.

**Comment by gdi2290** [comment] 2015-05-15 06:43
you can also get some huge perf gains, in terms of dom manipulation, by cloning rather than `.html()`/`.append()`

**Comment by jvandemo** [comment] 2015-05-15 07:10
I have added code to see a breakdown of how much milliseconds each step in the chain takes:
http://plnkr.co/edit/fbbs2aHsPcLof3ENQnml?p=preview

If you open the console, you can now see:
![breakdown](https://cloud.githubusercontent.com/assets/1859381/7648337/2cab9236-fae2-11e4-8620-710362e5252e.png)

Looks like most of the time is spent on transclusion.

**Comment by kentcdodds** [comment] 2015-05-15 12:53
Thanks for the help guys! I've spent a little bit of time trying to time things a little better. I'll have time to work on it more later.

**Comment by kentcdodds** [comment] 2015-05-16 21:16
So I was thinking that maybe the problem is the promise chain. So I created a new feature called `syncMode` which allows you to tell formly that you don't use `templateUrl` or need async support for your template manipulators. It's actually pretty neat. I have [a branch](https://github.com/formly-js/angular-formly/tree/features/syncMode) for it if you're interested in seeing what it takes to support. Wasn't a TON of work... Just a bit of work... Here's [the diff](https://github.com/formly-js/angular-formly/compare/master...features/syncMode?w=1)

Unfortunately... It doesn't make a lick of difference... http://output.jsbin.com/tawaxa/edit

I've all but determined that what's slow here is angular, not angular-formly... Someone please prove me wrong! Many apps need this to be faster...

**Comment by pmowrer** [comment] 2015-05-18 18:20
Like @jvandemo's said, based on his debugging it looks like significant time is spent in `trasncludeInWrappers`. Drilling into that method, it looks like the `forEach` on the `wrapper` array is the reason that the method is expensive, all of which appears to be validation/apiCheck? 

```javascript
          formlyUsability.checkWrapper(wrapper, options);
          wrapper.validateOptions && wrapper.validateOptions(options);
          runApiCheck(wrapper, options);
```

Its helpful to have better errors, but probably too expensive to run in a production environment, especially when every bit of performance improvement matters. @kentcdodds, is there an easy way to turn off `apiCheck`? There's a (hint in the docs)[http://docs.angular-formly.com/v6.4.0/docs/formlyconfig#disablewarnings] that alludes to the possibility, but I couldn't find an option.

**Comment by kentcdodds** [comment] 2015-05-18 18:23
Good point. Hadn't thought about disabling api-check for these perf tests. I'll add that to the most recent plunk...

**Comment by kentcdodds** [comment] 2015-05-18 18:33
Looks like it speeds it up by 2-3ms per field!

http://plnkr.co/edit/SyBNyZjF1XDo6wsDobj4?p=preview

It's definitely recommended to turn off api-check in production... To do so, see the [api-check docs](https://github.com/kentcdodds/api-check#disable-apicheck)

**Comment by kentcdodds** [comment] 2015-05-30 03:10
I'm going to go ahead and close this issue. If someone wants to try to figure out how angular-formly could be improved from a performance standpoint on something specific, that would be great, but I don't see this issue going anywhere at this time.

**Closed by kentcdodds** 2015-05-30 03:10 UTC
Labels: enhancement

**Comment by eufloyd** [comment] 2017-09-26 18:40
Hi, just as a hint. 

We were trying to solve a performance issue, and I tried some of the alternatives presented here, so I will tell what we did, it may help someone.

We had  performance issues on a form with 340+ fields. We use text input, selects, text areas, etc. The problem was, whenever we changed an input value, or changed a selected option, it took 5 seconds to update the model. During this time, the other select fields went blank and the browser went slow. 

We show the fields in different tabs, and each tab has it's formly form.

Solution:
We had and object called product as our ng-model, something like this:
`{"product":{"many":"fields" }}`

Now we  converted the object to array, and each array position is a not so big group of fields(object):
`{"product":["notSoManyFields":{"field:''value"} ]}`

Now the update is instantaneous, because not all the fields call digest on each change of value.
We needed to make the list an object again before persisting it, but it took little effort.

Hope it helps!
